<a href="https://colab.research.google.com/github/Dicky172/Alin/blob/master/sistem_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#selamat bertugas ya

#menggambar persamaan bidang dalam ruang 3D


#penyelesaian sistem linear
penyelesaian sistem persamaaan linear dengan menggunakan elominasi gauss.

selesaikan persmaan beikut
$$
8x_1+9x_2+x_3=19\\
x_1+2x_2+3x_3=9\\
2x_1+x_2+x_3=5\\
$$

Berikut penyelesaian diatas

In [3]:
import numpy as np
A=np.array ([[8,9,1,19],[1,2,3,9],[2,1,1,5]])


In [ ]:
import numpy as np
A=np.array ([[8,9,1,19],[1,2,3,9],[2,1,1,5]])

In [ ]:
[[ 1 -1  1  3]
 [ 2  1  8 18]
 [ 4  2 -3 -2]]


[[ 1.  -1.   1.   3. ]
 [ 2.   1.   8.  18. ]
 [ 2.   1.  -1.5 -1. ]]

#mendifinisikan fungsi operasi baris eliminasi gauss



*   RosSwap()
    hfielhfie
*   RowScale()
    bdjakkusdh
*   RowAdd()
    dgyahdqklw





In [6]:
def gauss_elimination(matrix):
    """
    Perform Gaussian Elimination on the given matrix.
    """
    n = len(matrix)


    for i in range(n):

        max_row = i
        for k in range(i + 1, n):
            if abs(matrix[k][i]) > abs(matrix[max_row][i]):
                max_row = k
        matrix[i], matrix[max_row] = matrix[max_row], matrix[i]


        for j in range(i + 1, n):
            factor = matrix[j][i] / matrix[i][i]
            for k in range(i, n + 1):
                matrix[j][k] -= factor * matrix[i][k]


    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = matrix[i][n] / matrix[i][i]
        for j in range(i):
            matrix[j][n] -= matrix[j][i] * x[i]

    return x


matrix = [
    [8,9,1,19],
 [1,2,3,9],
 [2,1,1,5]
]

solution = gauss_elimination(matrix)
print("Solution:", solution)


Solution: [1.0, 1.0, 2.0]
