#Aljabar Matriks

#tidak mengerjakan tidak boleh masuk

-berikan penjelasan apa itu matriks
-operasi matriks
-penjumlahan,perkalian,pengurangan, transpose matriks
-membuat program untuk mengalikan matriks a dan b

In [ ]:
import numpy as np
import sympy as sy

#Matriks 3x3

In [ ]:
a = np.array ([[1,2,3],[2,3,1],[2,4,3]])
print(a)

[[1 2 3]
 [2 3 1]
 [2 4 3]]


#matriks 3x2

In [ ]:
b = np.array([[5,4,6],[1,3,2],[6,4,7]])
print(b)

[[5 4 6]
 [1 3 2]]


#matriks 3x2

In [ ]:
c = np.array([[5,6],[4,3],[7,8]])
print(c)

[[5 6]
 [4 3]
 [7 8]]


#matriks d 3x3

In [ ]:
d = np.array([[4,3,5],[2,3,1],[7,6,5]])
print(d)

[[4 3 5]
 [2 3 1]
 [7 6 5]]


nxn matriks a
bxn matriks b

In [ ]:
a = np.array ([[1,2,3],[2,3,1],[2,4,3]])
print(a)
b = np.array([[5,4,6],[1,3,2],[6,4,7]])
print(b)
axb = a+b
print(axb)

[[1 2 3]
 [2 3 1]
 [2 4 3]]
[[5 4 6]
 [1 3 2]
 [6 4 7]]
[[ 6  6  9]
 [ 3  6  3]
 [ 8  8 10]]


In [ ]:
a = np.array ([[1,2,3],[2,3,1],[2,4,3]])
print(a)
ax2 = a*2
print(ax2)
print(ax2.shape)

[[1 2 3]
 [2 3 1]
 [2 4 3]]
[[2 4 6]
 [4 6 2]
 [4 8 6]]
(3, 3)


In [ ]:
a = np.array ([[1,2,3],[2,3,1],[2,4,3]])
print(a)
c = np.array([[5,6,7],[4,3,5],[7,8,2]])
print(c)
g = a*c
print(g)
print(g.shape)

[[1 2 3]
 [2 3 1]
 [2 4 3]]
[[5 6 7]
 [4 3 5]
 [7 8 2]]
[[ 5 12 21]
 [ 8  9  5]
 [14 32  6]]
(3, 3)


In [ ]:
a = np.array ([[1,2,3],[2,3,1],[2,4,3]])
print(a)
c = np.array([[5,6],[4,3],[7,8]])
print(c)
axc = a@b
print(axb)

[[1 2 3]
 [2 3 1]
 [2 4 3]]
[[5 6]
 [4 3]
 [7 8]]
[[25 22 31]
 [19 21 25]
 [32 32 41]]


In [ ]:
h=b@c
h=b@c
# a(bc)=(ab)c
i=a@h
j=a@b
k=j@c

In [ ]:
b = np.array([[5,4,6],[1,3,2],[6,4,7]])
print(b)
c = np.array([[5,6],[4,3],[7,8]])
print(c)


In [ ]:
covb