#Aljabar Matriks

In [ ]:
import numpy as np
import sympy as sy

#Matriks 3x3

In [4]:
a = np.array ([[1,2,3],[2,3,1],[2,4,3]])
print(a)

[[1 2 3]
 [2 3 1]
 [2 4 3]]


#matriks 3x2

In [5]:
b = np.array([[5,4,6],[1,3,2]])
print(b)

[[5 4 6]
 [1 3 2]]


#matriks 3x2

In [7]:
c = np.array([[5,6],[4,3],[7,8]])
print(c)

[[5 6]
 [4 3]
 [7 8]]


#matriks d 3x3

In [9]:
d = np.array([[4,3,5],[2,3,1],[7,6,5]])
print(d)

[[4 3 5]
 [2 3 1]
 [7 6 5]]


nxn matriks a
bxn matriks b