#Aljabar Matriks

#tidak mengerjakan tidak boleh masuk

#-berikan penjelasan apa itu matriks
#-operasi matriks
#-penjumlahan,perkalian,pengurangan, transpose matriks
#-membuat program untuk mengalikan matriks a dan b tanpa @

#Buat matriks A dan B dengan ordo 3x3 dan matriks C dengan ordo 2x3

#Apa itu matriks?

Matriks adalah kumpulan bilangan simbol atau ekspresi yang di sebut dengan elemen, yang membentuk persegi atau persegi panjang yang di susun menurut baris dan kolom

#Operasi Matriks

Ada beberapa operasi yang dapat di lakukan pada matriks:
-Penjumlahan
-Perkalian
-Pengurangan
-Transpose Matriks

In [ ]:
#Penjumlahan pada matriks
## Matriks dapat di jumlahan apabila memiliki ordo yang sama

import numpy as np
a = np.array(([1,2,3],[4,5,6]))
b = np.array(([7,6,5],[-1,-2,-3]))
print(a)

print(a+b)

[[1 2 3]
 [4 5 6]]
[[8 8 8]
 [3 3 3]]


In [ ]:
#Perkalian pada matriks
#Matriks bisa di kalikan jika kedua matriks memiliki jumlah baris dan kolom yang sama

import numpy as np

a = np.array(([1,2,3],[4,5,6],[4,5,6]))
b = np.array(([3,2,1],[-1,-2,-3],[7,5,6]))

print("matriks a: ")
print(a)
print("matriks b: ")
print(b)

c = np.dot(a,b)
print("matriks : c")
print(c)

matriks a: 
[[1 2 3]
 [4 5 6]
 [4 5 6]]
matriks b: 
[[ 3  2  1]
 [-1 -2 -3]
 [ 7  5  6]]
matriks : c
[[22 13 13]
 [49 28 25]
 [49 28 25]]


In [ ]:
#Pengurangan pada Matriks
## Matriks dapat di jumlahan apabila memiliki ordo yang sama

a = np.array(([1,2,3],[4,5,6]))
b = np.array(([7,6,5],[-1,-2,-3]))

print(a-b)

[[-6 -4 -2]
 [ 5  7  9]]


In [ ]:
#transpose matriks
## Transpose matriks membuat baris menjadi kolom
def trans(a):
   c = list(zip(*a))
   return c

def transs(a):
  for i in a:
   print(i)

a = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
     ]

print("matriks sebelum transpose :")
transs(a)
print("\n")
print("matriks sesudah di transpose")
b = trans(a)
transs(b)



matriks sebelum transpose :
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


matriks sesudah di transpose
(1, 4, 7)
(2, 5, 8)
(3, 6, 9)


In [1]:
#perkalian matruks tanpa import numpy

def matrix_kali(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        print("ordo eror")
        return None

    hasil = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]

    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                hasil[i][j] += matrix1[i][k] * matrix2[k][j]

    return hasil

matrix1 = [[1, 2, 3],
           [4, 5, 6]]

matrix2 = [[7, 6],
           [5, -1],
           [-2, -3]]

hasil_matrix = matrix_kali(matrix1, matrix2)

if hasil_matrix:
    print("hasil perkalian matriks")
    for row in hasil_matrix:
        print(row)


hasil perkalian matriks
[11, -5]
[41, 1]
